# Add executables
add_executable(testCirclesDistr archive/circleDistroTest.cpp)
add_executable(testCollision archive/intersectionTest.cpp)
add_executable(testCollisionDLA archive/collisionDLA.cpp)
add_executable(testCollisionRandomCircles archive/collisionRandomCircles.cpp)
add_executable(testCollisionStopper archive/otherMethods/CircleCollisionStopper.cpp)
add_executable(testDiffusion archive/diffusion.cpp)
add_executable(testDiffusionNew archive/diffusionNew.cpp)
# add_executable(testMC mc/mainMC.cpp)
add_executable(testMD md/mainMD.cpp)
add_executable(testMDaggregation md/mainMDaggregation.cpp)
add_executable(testStopperRandomCircles archive/otherMethods/circleStopperRandomTest.cpp)
add_executable(testVecMat archive/testVecMat.cpp)

# Link libraries
target_link_libraries(testCirclesDistr adios2::cxx11)
target_link_libraries(testCollision adios2::cxx11)
target_link_libraries(testCollisionDLA adios2::cxx11)
target_link_libraries(testCollisionRandomCircles adios2::cxx11)
target_link_libraries(testCollisionStopper adios2::cxx11)
target_link_libraries(testDiffusionNew adios2::cxx11)
# target_link_libraries(testMC adios2::cxx11)
# target_link_libraries(testMC Boost::program_options adios2::cxx11)
target_link_libraries(testMD Boost::program_options adios2::cxx11)
target_link_libraries(testDiffusionNew Boost::program_options adios2::cxx11)
target_link_libraries(testMDaggregation Boost::program_options adios2::cxx11)
target_link_libraries(testStopperRandomCircles adios2::cxx11)
target_link_libraries(testVecMat adios2::cxx11)
