# Add executables
add_executable(testCirclesDistr collision/circleDistroTest.cpp)
add_executable(testCollision collision/intersectionTest.cpp)
add_executable(testCollisionDLA collision/collisionDLA.cpp)
add_executable(testCollisionRandomCircles collision/collisionRandomCircles.cpp)
add_executable(testCollisionStopper collision/otherMethods/CircleCollisionStopper.cpp)
add_executable(testDiffusion mc/diffusion.cpp)
add_executable(testMC mc/mainMC.cpp)
add_executable(testMD md/mainMD.cpp)
add_executable(testMDaggregation md/mainMDaggregation.cpp)
add_executable(testPlotForcePotential md/plotForcePotential.cpp)
add_executable(testStopperRandomCircles collision/otherMethods/circleStopperRandomTest.cpp)
add_executable(testVecMat testVecMat.cpp)

# Link libraries
target_link_libraries(testCirclesDistr adios2::cxx11)
target_link_libraries(testCollision adios2::cxx11)
target_link_libraries(testCollisionDLA adios2::cxx11)
target_link_libraries(testCollisionRandomCircles adios2::cxx11)
target_link_libraries(testCollisionStopper adios2::cxx11)
target_link_libraries(testMC adios2::cxx11)
target_link_libraries(testMC Boost::program_options adios2::cxx11)
target_link_libraries(testMD Boost::program_options adios2::cxx11)
target_link_libraries(testMDaggregation Boost::program_options adios2::cxx11)
target_link_libraries(testPlotForcePotential adios2::cxx11)
target_link_libraries(testStopperRandomCircles adios2::cxx11)
target_link_libraries(testVecMat adios2::cxx11)
