add_executable(testVecMat testVecMat.cpp)
add_executable(testDiffusion diffusion/diffusion.cpp)
add_executable(testCollision collision/intersectionTest.cpp)
add_executable(testCirclesDistr collision/circleDistroTest.cpp)
add_executable(testCollisionPBC collision/otherMethods/collisionPBC.cpp)
add_executable(testCollisionStopper collision/otherMethods/CircleCollisionStopper.cpp)
add_executable(testStopperRandomCircles collision/otherMethods/circleStopperRandomTest.cpp)
add_executable(testCollisionRandomCircles collision/collisionRandomCircles.cpp)
add_executable(testCollisionDLA collision/collisionDLA.cpp)
add_executable(testNParticleMD trajectory/nParticleMD.cpp)
target_link_libraries(testNParticleMD Boost::program_options)
add_executable(testPlotForcePotential trajectory/plotForcePotential.cpp)